/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import javax.swing.JEditorPane;
import javax.swing.JPanel;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author JUAN DIEGO ALVARADO
 */
public class RCARROS extends javax.swing.JFrame {

    /**
     * Creates new form RCARROS
     */
    public RCARROS() {
        initComponents();                    Listas.listaClientesGeneral.setjTable1(jTable1);
        Listas.listaClientesGeneral.Carros2(ListaClientes.NombreCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Foto", "Registro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
  public int Buscar (Object Cliente){
   int c=0;
      for (int i = 0; i <jTable1.getRowCount() ; i++) {
          if (jTable1.getValueAt(i, 1).toString().equalsIgnoreCase(Cliente.toString())) {
              c++;
          }
  
      }
return c;  }
public void GenerarReporteRepuestos(JEditorPane _ContenedorHTML) {
        NodoCarros InicioAux = Listas.listaCarros.Inicio;
        String FilaTabla = "";
        String HTML = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "    <head>\n"
                + "        <title>Reporte Repuestos</title>\n"
                + "    </head>\n"
                + "    <body>\n"
                + "    <center>\n"
                + "        <h1 class=\"h\"> Reporte Repuestos</h1>\n"
                + "        <table class=\"blueTable\" style=\"width: 80%\" border=\"\">\n"
                + "            <thead>\n"
                  + "                <tr>\n"
                + "                    <td>PLACA</td>\n"
                + "                    <td>MARCA</td>\n"
                + "                    <td>MODELO</td>\n"
                + "                    <td>FOTO</td>\n"    
                +"                       <td>E</td>\n"
               
                + "                          </tr> \n"
                + "            </thead>\n"
                + "ContenidoTabla\n"//Todas las filas de la tabla 
                + "        </table>   \n"
                + "    </center>\n"
                + "</body>\n"
                + "</html>";
    for (int i = 0;  i< jTable1.getRowCount(); i++) {
        
            System.out.println(InicioAux.getPlaca());
            FilaTabla += " <tr>\n"
                    + "    <td>" + jTable1.getValueAt(i, 0)+ "</td>\n"
                    + "    <td>" + jTable1.getValueAt(i, 1)+ "</td>\n"
                    + "    <td>" + jTable1.getValueAt(i, 2)+ "</td>\n"
                    + "    <td>" + jTable1.getValueAt(i, 3)+ "</td>\n"
                    + "    <td>" + jTable1.getValueAt(i, 4)+ "</td>\n" + "   "
                  
                    
                    
                    + "  </tr>\n";
        
    }
  
         
        //Agregamos el contenido de la tabla al html
        String ReporteHTML = HTML.replace("ContenidoTabla", FilaTabla);
        _ContenedorHTML.setContentType("text/html");
        _ContenedorHTML.setText("");
        HTMLEditorKit kit = new HTMLEditorKit();
        StyleSheet styleSheet = kit.getStyleSheet();
        //Reglas CSS
        styleSheet.addRule("body{background: #FE9A2E;}");

        javax.swing.text.Document doc = kit.createDefaultDocument();
        _ContenedorHTML.setEditable(false);
        _ContenedorHTML.setDocument(doc);
        _ContenedorHTML.setText(ReporteHTML);

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GenerarGrafica(jPanel1);

        GenerarReporteRepuestos(jEditorPane1);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void GenerarGrafica(JPanel _ContenedorGrafica) {
        DefaultPieDataset DatosGrafica = new DefaultPieDataset();
        NodoClientes InicioAux = Listas.listaClientesGeneral.getInicio();
      
        Object [ ]TiposdeCliente={"Oro","Normal"};
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        
    
               
           Double existencias = Double.valueOf("" + Buscar(jTable1.getValueAt(i, 1)));
            String NombreRepuesto = jTable1.getValueAt(i, 1).toString();
            DatosGrafica.setValue(NombreRepuesto, existencias);

            InicioAux = InicioAux.getSiguiente();

        
        
           }

        JFreeChart chart = ChartFactory.createPieChart3D("Clientes", DatosGrafica, true, false, false);
        ChartPanel PanelGrafico = new ChartPanel(chart);
        PanelGrafico.setBounds(10, 10, _ContenedorGrafica.getWidth() - 50, _ContenedorGrafica.getHeight() - 50);
        PanelGrafico.setMouseWheelEnabled(true);
        _ContenedorGrafica.add(PanelGrafico);
        _ContenedorGrafica.repaint();
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RCARROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RCARROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RCARROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RCARROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RCARROS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
