/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import com.sun.org.apache.xalan.internal.xsltc.compiler.Template;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.locale.provider.AuxLocaleProviderAdapter;

/**
 *
 * @author JUAN DIEGO ALVARADO
 */
public class RegistroClientes extends javax.swing.JFrame {

    public static String[][] re = new String[1][4];
    public int r ;
    Random R = new Random();

    /**
     * Creates new form RegistroClientes
     */
    public RegistroClientes() {
        initComponents();
        NodoClientes aux = new NodoClientes();
        Listas.listaClientesGeneral.setjTable1(jTable1);
        Listas.listaClientesGeneral.Carros(ListaClientes.NombreCliente);

        Listas.listaClientesGeneral.Carros(ListaClientes.TipoCliente);

            Listas.ListaServiciosGeneral.setTabla(jTable2);
            Listas.ListaServiciosGeneral.Servicios();

        jLabel2.setText(Listas.listaClientesGeneral.NombreCliente);
jLabel4.setText(Listas.listaClientesGeneral.TipoCliente);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Foto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("Nombre");

        jButton1.setText("Ver los Vehiculos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("DPI:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", " Marca", "Modelo", "Precio", "IDservicio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setText("jLabel5");

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jButton1)
                        .addGap(176, 176, 176)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(95, 95, 95)
                        .addComponent(jButton3)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jButton2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jButton4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(348, 348, 348))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Registrar();
       
       
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        String Placa = String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(), 0));
               String modelA = String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(), 2));
        String marcaA = String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(), 1));

        String Foto = String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(), 3));
              ImageIcon fot = new ImageIcon(Foto);
        
        jLabel5.setIcon(fot);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Listas.LstAtencion.imprimir();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  Listas.listaColas.imprimir();        // TODO add your handling code here:
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    
public void Registrar(){
    
        NodoSevicio Nodo = new NodoSevicio();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        String Placa = String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(), 0));
               String marcaA = String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(), 2));
        String modelA = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();

        String Foto = String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(), 3));
        DefaultTableModel modelo2 = (DefaultTableModel) jTable2.getModel();
        String NombreS = String.valueOf(modelo2.getValueAt(jTable2.getSelectedRow(), 0));

        String modelS = String.valueOf(modelo2.getValueAt(jTable2.getSelectedRow(), 1));

        String marcaS = String.valueOf(modelo2.getValueAt(jTable2.getSelectedRow(), 2));

        String precio = String.valueOf(modelo2.getValueAt(jTable2.getSelectedRow(), 3));
String id = String.valueOf(modelo2.getValueAt(jTable2.getSelectedRow(), 4));
  

        
        
          if (NombreS.equalsIgnoreCase("Diagnostico")) {
            System.out.println("prueba1");
            r++;
            r = R.nextInt(jTable2.getRowCount());

            while (!jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().equalsIgnoreCase(jTable2.getValueAt(r, 1).toString()) && !
                    jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString().equalsIgnoreCase(jTable2.getValueAt(r, 2).toString())) {

                JOptionPane.showConfirmDialog(null, "Servicio o Modelo no son iguales al carro");
                r = R.nextInt(jTable2.getRowCount());
                
}
System.out.println("prueba2");
                       if(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().equalsIgnoreCase(jTable2.getValueAt(r, 1).toString()) && jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString().equalsIgnoreCase(jTable2.getValueAt(r, 2).toString())) {
    String S= (jTable2.getValueAt(r, 0)).toString();
    String S2=(jTable2.getValueAt(r, 3).toString());
         alamacenar(Listas.listaClientesGeneral.DPI);
    Listas.ListaServiciosGeneral.D(Double.parseDouble(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString()));
//meter metodo             
                         
  System.out.println("prueba3");
                
             if (Listas.LstAtencion.EstaVacia()) {
          Listas.LstAtencion.agregar(Listas.listaClientesGeneral.NombreCliente, Listas.listaClientesGeneral.TipoCliente, Placa,S,S2);
              
             }else       {
                 if (Listas.listaClientesGeneral.TipoCliente.equalsIgnoreCase("Oro")) {
  System.out.println(" prueba4"); 
                        Listas.listaColas.agregar(Listas.listaClientesGeneral.NombreCliente, Listas.listaClientesGeneral.TipoCliente, Placa,S, S2);

                    }  else  {
  System.out.println("prueba5");  System.out.println((jTable2.getValueAt(r, 0))+"                 "+ (jTable2.getValueAt(r, 3).toString()));   
                        Listas.listaColas.agregarFINAL(Listas.listaClientesGeneral.NombreCliente, Listas.listaClientesGeneral.TipoCliente, Placa,S, S2);
  System.out.println("prueba6");  System.out.println((jTable2.getValueAt(r, 0))+"                 "+ (jTable2.getValueAt(r, 3).toString()));   
                    }
             }          
   
        }
     
         }
        
        
        
        
          else if ( jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().equalsIgnoreCase(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString() ) &&  jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString().equalsIgnoreCase(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString() )) {
    Listas.ListaServiciosGeneral.D(Double.parseDouble(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString()));            alamacenar(Listas.listaClientesGeneral.DPI);//meter metodo                  //meter
    String O = "Oro";
    if (Listas.LstAtencion.EstaVacia()) {    Listas.LstAtencion.agregar(Listas.listaClientesGeneral.NombreCliente, Listas.listaClientesGeneral.TipoCliente, Placa, NombreS, precio);
                
  System.out.println("prueba1");

                }                else { if (Listas.listaClientesGeneral.TipoCliente.equalsIgnoreCase(O)) {
  System.out.println("prueba2");
                        Listas.listaColas.agregar(Listas.listaClientesGeneral.NombreCliente, Listas.listaClientesGeneral.TipoCliente, Placa, NombreS, precio);

                    } else{
  System.out.println("prueba3");
                        Listas.listaColas.agregarFINAL(Listas.listaClientesGeneral.NombreCliente, Listas.listaClientesGeneral.TipoCliente, Placa, NombreS, precio);
  System.out.println("prueba4");
                    }
                }         

        System.out.println("prueba1");        
 }
else{
      System.out.println("fallo");
  }
            // TODO adout   d your handling code here:
    
}
public void  alamacenar(Object Dpi){
    NodoClientes Nodo = Listas.listaClientesGeneral.Inicio;
    do {if (Listas.listaClientesGeneral.DPI.toString().equalsIgnoreCase(Dpi.toString()) ){
            Nodo.setRegistro(Nodo.getRegistro()+1);
            if (Nodo.getRegistro()==3){
            Nodo.setTipoCliente("Oro");
        }
        }Nodo=Nodo.siguiente;
        
        
        
    } while (Nodo!=Listas.listaClientesGeneral.Inicio);
   
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
